# Configurazione di Vagrant per creare due macchine virtuali Ubuntu
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

#Impostazione del provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

#Definizione delle macchine virtuali 
#ciascuna con il proprio indirizzo IP e hostname
#ed eseguendo uno script di provisioning per installare Docker
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.56.11"
    node1.vm.hostname = "node1"
    node1.vm.provision "shell", path: "install_docker.sh"
  end

# Definizione della seconda macchina virtuale
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.56.12"
    node2.vm.hostname = "node2"
    node2.vm.provision "shell", path: "install_docker.sh"
  end
end

